
urls = {'index': '/',
'index_zh': '/?language=zh',
'search': '/search/',
'search_zh': '/search/?language=zh',
'update':'/update/',
'update_zh':'/update/?language=zh',
"getAccount":"/getAccount/",
"getPW":"/getPW/",
"Save_Result_to_sql":"/Save_Result_to_sql/",
"Search_item":"/Search_item",
"Update_Text":"/Update_Text",
"Delete_Item":"/Delete_Item",
"Restore":"/Restore/",
"Restore_zh":"/Restore/?language=zh",
"Login":"/Login/",
}
