
urls = {'index': '/',
'index_zh': '/?language=zh',
'search': '/search/',
'search_zh': '/search/?language=zh',
'update':'/update/',
'update_zh':'/update/?language=zh',
"getAccount":"/getAccount/",
"getPD1":"/getPD/1",
"getPD2":"/getPD/2",
"getPD3":"/getPD/3",
"getPD4":"/getPD/4",
"Save_Result_to_sql":"/Save_Result_to_sql",
"Search_item":"/Search_item",
}
